### PR TITLE
fix: fiat deposit fixes

### LINKED ISSUE #93: better error handling on the fiat payment form
- validation error messages are too technical
- catch possible runtime errors, try to recover and display human friendly message

### LINKED ISSUE #94: fiat topup: check payment is processed by Circle before requesting faucet
after creating a payment, the frontend needs to wait and poll the API, until the payment is confirmed.

related code section: https://github.com/WhiteRabbitTheWorldIsYours/mad-hatter/blob/develop/packages/burner-plugin/src/ui/topupPage/index.tsx#L164-L166

=> otherwise there is a race condition, and the faucet will be always flaky.

### LINKED ISSUE #130: fiat topup: CVV verification fails for existing card
To reproduce:
1. Register a card (make a deposit by entering your credit card and billing data in WR app)
2. Try making a second deposit — you will be prompted to fill a reduced form (only amount and CVV)

**Expected:**
deposit goes through and balance in WR app increases

**Actual:**
Circle returns "CVV is invalid" error

### PR DESCRIPTION
**Pull request by troggy**
Please remember the [Contributing Guidelines](https://github.com/leapdao/meta/blob/master/CONTRIBUTION.md) :heart:

## What does this PR do?

- poll Circle `payments` API until the payment is confirmed (capped by 4 seconds). Request the XDAI faucet only once confirmed
- add a simple error handling view. Display a generic message + a technical code returned from Circle.
- fixed an error with CVV processing on a PaymentForm
- added a more human readable error messages for NewCardPaymentForm and PaymentForm
- simplified home-grown expiry date validation

## Recommendations for testing

Circle Sandbox payment will succeed with any CVV (even if not matching the one on the card). Temporary change `createAndSubmitPayment` in TopupPage to use `null` CVV for Circle to return CVV error.

Temporary change error code in `decodeCircleError` to see the generic error screen.

## Links to relevant issues or information
Closes #94 
Closes #130 
Closes #93

### CODE REVIEW

**Comment by troggy** [comment]
Better error handling

image

image

**Comment by troggy** [comment]
New screen to show errors from Circle API:

image

File: packages/burner-plugin/src/ui/topupPage/index.tsx [hunk 1]
```diff
@@ -161,12 +175,24 @@ const TopUpPage = (context: TopupPageProps) => {
       walletAddress: accounts[0],
     };
     console.log(params);
```
Comment (Clearwood) [inline packages/burner-plugin/src/ui/topupPage/index.tsx:177]: maybe we could remove the logs?

Comment (troggy) [reply packages/burner-plugin/src/ui/topupPage/index.tsx:177]: maybe it would be good to have those in production for a while until fiat deposits are working solid ? So we can debug broken deposits right away. What do you think?
